name: flutter_bloc_test_2
description: A new Flutter project using Bloc.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations:
  auto_route: ^2.4.1
  connectivity: ^3.0.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.0
  flutter_bloc: ^7.0.0
  freezed_annotation:
  flutter_essentials_kit: ^2.1.1
  retrofit: ^3.0.1+1
  intl: ^0.17.0
  json_annotation: ^4.5.0
  pretty_dio_logger: ^1.2.0-beta-1
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  auto_route_generator:
  build_runner:
  flutter_lints: ^1.0.0
  freezed:
  json_serializable: ^6.1.5
  retrofit_generator: ^3.0.1+1

flutter:

  generate: true
  uses-material-design: true
